package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asentamientos generated by hbm2java
 */
@Entity
@Table(name="ASENTAMIENTOS"
    ,catalog="astecadb"
)
public class Asentamientos  implements java.io.Serializable {


     private AsentamientosId id;
     private Municipios municipios;
     private Integer idCp;
     private String nombre;
     private Short activo;
     private String clave;
     private Set<Domicilios> domicilioses = new HashSet<Domicilios>(0);

    public Asentamientos() {
    }

	
    public Asentamientos(AsentamientosId id, Municipios municipios) {
        this.id = id;
        this.municipios = municipios;
    }
    public Asentamientos(AsentamientosId id, Municipios municipios, Integer idCp, String nombre, Short activo, String clave, Set<Domicilios> domicilioses) {
       this.id = id;
       this.municipios = municipios;
       this.idCp = idCp;
       this.nombre = nombre;
       this.activo = activo;
       this.clave = clave;
       this.domicilioses = domicilioses;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idAsentamiento", column=@Column(name="ID_ASENTAMIENTO", nullable=false) ), 
        @AttributeOverride(name="idMunicipio", column=@Column(name="ID_MUNICIPIO", nullable=false) ), 
        @AttributeOverride(name="idEstado", column=@Column(name="ID_ESTADO", nullable=false) ) } )
    public AsentamientosId getId() {
        return this.id;
    }
    
    public void setId(AsentamientosId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_MUNICIPIO", referencedColumnName="ID_MUNICIPIO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ID_ESTADO", referencedColumnName="ID_ESTADO", nullable=false, insertable=false, updatable=false) } )
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }
    
    @Column(name="ID_CP")
    public Integer getIdCp() {
        return this.idCp;
    }
    
    public void setIdCp(Integer idCp) {
        this.idCp = idCp;
    }
    
    @Column(name="NOMBRE", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="ACTIVO")
    public Short getActivo() {
        return this.activo;
    }
    
    public void setActivo(Short activo) {
        this.activo = activo;
    }
    
    @Column(name="CLAVE", length=15)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="asentamientos")
    public Set<Domicilios> getDomicilioses() {
        return this.domicilioses;
    }
    
    public void setDomicilioses(Set<Domicilios> domicilioses) {
        this.domicilioses = domicilioses;
    }




}


