package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name="bitacora"
    ,catalog="astecadb"
)
public class Bitacora  implements java.io.Serializable {


     private long idBitacora;
     private Date fecha;
     private String ip;
     private Integer idUsr;
     private String mensaje;
     private String accion;

    public Bitacora() {
    }

	
    public Bitacora(long idBitacora) {
        this.idBitacora = idBitacora;
    }
    public Bitacora(long idBitacora, Date fecha, String ip, Integer idUsr, String mensaje, String accion) {
       this.idBitacora = idBitacora;
       this.fecha = fecha;
       this.ip = ip;
       this.idUsr = idUsr;
       this.mensaje = mensaje;
       this.accion = accion;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_BITACORA", unique=true, nullable=false)
    public long getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(long idBitacora) {
        this.idBitacora = idBitacora;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="IP", length=15)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    
    @Column(name="ID_USR")
    public Integer getIdUsr() {
        return this.idUsr;
    }
    
    public void setIdUsr(Integer idUsr) {
        this.idUsr = idUsr;
    }
    
    @Column(name="MENSAJE", length=50)
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    
    @Column(name="ACCION", length=30)
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }




}


