package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CalifCursos generated by hbm2java
 */
@Entity
@Table(name="calif_cursos"
    ,catalog="astecadb"
)
public class CalifCursos  implements java.io.Serializable {


     private long idCalifCurso;
     private Alumnos alumnos;
     private Cursos cursos;
     private Materias materias;
     private BigDecimal calificacion;

    public CalifCursos() {
    }

	
    public CalifCursos(long idCalifCurso) {
        this.idCalifCurso = idCalifCurso;
    }
    public CalifCursos(long idCalifCurso, Alumnos alumnos, Cursos cursos, Materias materias, BigDecimal calificacion) {
       this.idCalifCurso = idCalifCurso;
       this.alumnos = alumnos;
       this.cursos = cursos;
       this.materias = materias;
       this.calificacion = calificacion;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CALIF_CURSO", unique=true, nullable=false)
    public long getIdCalifCurso() {
        return this.idCalifCurso;
    }
    
    public void setIdCalifCurso(long idCalifCurso) {
        this.idCalifCurso = idCalifCurso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ALUMNO")
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CURSO")
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MATERIA")
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }
    
    @Column(name="CALIFICACION", precision=4)
    public BigDecimal getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(BigDecimal calificacion) {
        this.calificacion = calificacion;
    }




}


