package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Capacidades generated by hbm2java
 */
@Entity
@Table(name="capacidades"
    ,catalog="astecadb"
)
public class Capacidades  implements java.io.Serializable {


     private int idCapacidad;
     private TiposLicencia tiposLicencia;
     private String tipoCapacidad;
     private String autorizada;
     private Integer horas;
     private Date fechaInic;
     private Date fechaFin;
     private String acreditada;
     private Set<CapacidadesAlumnos> capacidadesAlumnoses = new HashSet<CapacidadesAlumnos>(0);

    public Capacidades() {
    }

	
    public Capacidades(int idCapacidad) {
        this.idCapacidad = idCapacidad;
    }
    public Capacidades(int idCapacidad, TiposLicencia tiposLicencia, String tipoCapacidad, String autorizada, Integer horas, Date fechaInic, Date fechaFin, String acreditada, Set<CapacidadesAlumnos> capacidadesAlumnoses) {
       this.idCapacidad = idCapacidad;
       this.tiposLicencia = tiposLicencia;
       this.tipoCapacidad = tipoCapacidad;
       this.autorizada = autorizada;
       this.horas = horas;
       this.fechaInic = fechaInic;
       this.fechaFin = fechaFin;
       this.acreditada = acreditada;
       this.capacidadesAlumnoses = capacidadesAlumnoses;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CAPACIDAD", unique=true, nullable=false)
    public int getIdCapacidad() {
        return this.idCapacidad;
    }
    
    public void setIdCapacidad(int idCapacidad) {
        this.idCapacidad = idCapacidad;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_LICENCIA")
    public TiposLicencia getTiposLicencia() {
        return this.tiposLicencia;
    }
    
    public void setTiposLicencia(TiposLicencia tiposLicencia) {
        this.tiposLicencia = tiposLicencia;
    }
    
    @Column(name="TIPO_CAPACIDAD", length=50)
    public String getTipoCapacidad() {
        return this.tipoCapacidad;
    }
    
    public void setTipoCapacidad(String tipoCapacidad) {
        this.tipoCapacidad = tipoCapacidad;
    }
    
    @Column(name="AUTORIZADA", length=50)
    public String getAutorizada() {
        return this.autorizada;
    }
    
    public void setAutorizada(String autorizada) {
        this.autorizada = autorizada;
    }
    
    @Column(name="HORAS")
    public Integer getHoras() {
        return this.horas;
    }
    
    public void setHoras(Integer horas) {
        this.horas = horas;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INIC", length=10)
    public Date getFechaInic() {
        return this.fechaInic;
    }
    
    public void setFechaInic(Date fechaInic) {
        this.fechaInic = fechaInic;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FIN", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    
    @Column(name="ACREDITADA", length=15)
    public String getAcreditada() {
        return this.acreditada;
    }
    
    public void setAcreditada(String acreditada) {
        this.acreditada = acreditada;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="capacidades")
    public Set<CapacidadesAlumnos> getCapacidadesAlumnoses() {
        return this.capacidadesAlumnoses;
    }
    
    public void setCapacidadesAlumnoses(Set<CapacidadesAlumnos> capacidadesAlumnoses) {
        this.capacidadesAlumnoses = capacidadesAlumnoses;
    }




}


