package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Certificados generated by hbm2java
 */
@Entity
@Table(name="certificados"
    ,catalog="astecadb"
)
public class Certificados  implements java.io.Serializable {


     private int idCert;
     private Alumnos alumnos;
     private Estatus estatus;
     private String noCertificado;
     private Date fechaEmision;
     private Date fechaCancelacion;
     private String motivoCancelacion;

    public Certificados() {
    }

	
    public Certificados(int idCert) {
        this.idCert = idCert;
    }
    public Certificados(int idCert, Alumnos alumnos, Estatus estatus, String noCertificado, Date fechaEmision, Date fechaCancelacion, String motivoCancelacion) {
       this.idCert = idCert;
       this.alumnos = alumnos;
       this.estatus = estatus;
       this.noCertificado = noCertificado;
       this.fechaEmision = fechaEmision;
       this.fechaCancelacion = fechaCancelacion;
       this.motivoCancelacion = motivoCancelacion;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CERT", unique=true, nullable=false)
    public int getIdCert() {
        return this.idCert;
    }
    
    public void setIdCert(int idCert) {
        this.idCert = idCert;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ALUMNO")
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ESTATUS")
    public Estatus getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Estatus estatus) {
        this.estatus = estatus;
    }
    
    @Column(name="NO_CERTIFICADO", length=50)
    public String getNoCertificado() {
        return this.noCertificado;
    }
    
    public void setNoCertificado(String noCertificado) {
        this.noCertificado = noCertificado;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_EMISION", length=10)
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CANCELACION", length=10)
    public Date getFechaCancelacion() {
        return this.fechaCancelacion;
    }
    
    public void setFechaCancelacion(Date fechaCancelacion) {
        this.fechaCancelacion = fechaCancelacion;
    }
    
    @Column(name="MOTIVO_CANCELACION", length=150)
    public String getMotivoCancelacion() {
        return this.motivoCancelacion;
    }
    
    public void setMotivoCancelacion(String motivoCancelacion) {
        this.motivoCancelacion = motivoCancelacion;
    }




}


