package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CursosMaterias generated by hbm2java
 */
@Entity
@Table(name="cursos_materias"
    ,catalog="astecadb"
)
public class CursosMaterias  implements java.io.Serializable {


     private int idCursoMateria;
     private Cursos cursos;
     private Materias materias;

    public CursosMaterias() {
    }

	
    public CursosMaterias(int idCursoMateria) {
        this.idCursoMateria = idCursoMateria;
    }
    public CursosMaterias(int idCursoMateria, Cursos cursos, Materias materias) {
       this.idCursoMateria = idCursoMateria;
       this.cursos = cursos;
       this.materias = materias;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CURSO_MATERIA", unique=true, nullable=false)
    public int getIdCursoMateria() {
        return this.idCursoMateria;
    }
    
    public void setIdCursoMateria(int idCursoMateria) {
        this.idCursoMateria = idCursoMateria;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CURSO")
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MATERIA")
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }




}


