package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocsNecesariosAlumnos generated by hbm2java
 */
@Entity
@Table(name="DOCS_NECESARIOS_ALUMNOS"
    ,catalog="astecadb"
)
public class DocsNecesariosAlumnos  implements java.io.Serializable {


     private short idDocNec;
     private String nombre;

    public DocsNecesariosAlumnos() {
    }

	
    public DocsNecesariosAlumnos(short idDocNec) {
        this.idDocNec = idDocNec;
    }
    public DocsNecesariosAlumnos(short idDocNec, String nombre) {
       this.idDocNec = idDocNec;
       this.nombre = nombre;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_DOC_NEC", unique=true, nullable=false)
    public short getIdDocNec() {
        return this.idDocNec;
    }
    
    public void setIdDocNec(short idDocNec) {
        this.idDocNec = idDocNec;
    }
    
    @Column(name="NOMBRE", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


