package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domicilios generated by hbm2java
 */
@Entity
@Table(name="DOMICILIOS"
    ,catalog="astecadb"
)
public class Domicilios  implements java.io.Serializable {


     private int idDomicilio;
     private Asentamientos asentamientos;
     private String calle;
     private String noExterior;
     private String noInterior;
     private Integer cp;
     private String telefono;
     private Set<Administrativos> administrativoses = new HashSet<Administrativos>(0);
     private Set<Referencias> referenciases = new HashSet<Referencias>(0);
     private Set<Instructores> instructoreses = new HashSet<Instructores>(0);
     private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);

    public Domicilios() {
    }

	
    public Domicilios(int idDomicilio) {
        this.idDomicilio = idDomicilio;
    }
    public Domicilios(int idDomicilio, Asentamientos asentamientos, String calle, String noExterior, String noInterior, Integer cp, String telefono, Set<Administrativos> administrativoses, Set<Referencias> referenciases, Set<Instructores> instructoreses, Set<Alumnos> alumnoses) {
       this.idDomicilio = idDomicilio;
       this.asentamientos = asentamientos;
       this.calle = calle;
       this.noExterior = noExterior;
       this.noInterior = noInterior;
       this.cp = cp;
       this.telefono = telefono;
       this.administrativoses = administrativoses;
       this.referenciases = referenciases;
       this.instructoreses = instructoreses;
       this.alumnoses = alumnoses;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_DOMICILIO", unique=true, nullable=false)
    public int getIdDomicilio() {
        return this.idDomicilio;
    }
    
    public void setIdDomicilio(int idDomicilio) {
        this.idDomicilio = idDomicilio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ASENTAMIENTO", referencedColumnName="ID_ASENTAMIENTO"), 
        @JoinColumn(name="ID_MUNICIPIO", referencedColumnName="ID_MUNICIPIO"), 
        @JoinColumn(name="ID_ESTADO", referencedColumnName="ID_ESTADO") } )
    public Asentamientos getAsentamientos() {
        return this.asentamientos;
    }
    
    public void setAsentamientos(Asentamientos asentamientos) {
        this.asentamientos = asentamientos;
    }
    
    @Column(name="CALLE", length=30)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    
    @Column(name="NO_EXTERIOR", length=10)
    public String getNoExterior() {
        return this.noExterior;
    }
    
    public void setNoExterior(String noExterior) {
        this.noExterior = noExterior;
    }
    
    @Column(name="NO_INTERIOR", length=10)
    public String getNoInterior() {
        return this.noInterior;
    }
    
    public void setNoInterior(String noInterior) {
        this.noInterior = noInterior;
    }
    
    @Column(name="CP")
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }
    
    @Column(name="TELEFONO", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilios")
    public Set<Administrativos> getAdministrativoses() {
        return this.administrativoses;
    }
    
    public void setAdministrativoses(Set<Administrativos> administrativoses) {
        this.administrativoses = administrativoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilios")
    public Set<Referencias> getReferenciases() {
        return this.referenciases;
    }
    
    public void setReferenciases(Set<Referencias> referenciases) {
        this.referenciases = referenciases;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilios")
    public Set<Instructores> getInstructoreses() {
        return this.instructoreses;
    }
    
    public void setInstructoreses(Set<Instructores> instructoreses) {
        this.instructoreses = instructoreses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilios")
    public Set<Alumnos> getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set<Alumnos> alumnoses) {
        this.alumnoses = alumnoses;
    }




}


