package mx.com.asteca.persistencia.entidades;
// Generated 26/09/2013 09:21:28 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InstructoresMaterias generated by hbm2java
 */
@Entity
@Table(name="INSTRUCTORES_MATERIAS"
    ,catalog="astecadb"
)
public class InstructoresMaterias  implements java.io.Serializable {


     private Integer idInstructorMateria;
     private Instructores instructores;
     private MateriasRegistros materias;

    public InstructoresMaterias() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID_INSTRUCTOR_MATERIA", unique=true, nullable=false)
    public Integer getIdInstructorMateria() {
        return this.idInstructorMateria;
    }
    
    public void setIdInstructorMateria(Integer idInstructorMateria) {
        this.idInstructorMateria = idInstructorMateria;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_INSTRUCTOR")
    public Instructores getInstructores() {
        return this.instructores;
    }
    
    public void setInstructores(Instructores instructores) {
        this.instructores = instructores;
    }


	/**
	 * @return the materias
	 */
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MATERIA_REGISTRO")
	public MateriasRegistros getMaterias() {
		return materias;
	}


	/**
	 * @param materias the materias to set
	 */
	public void setMaterias(MateriasRegistros materias) {
		this.materias = materias;
	}
    

}


