package mx.com.asteca.persistencia.entidades;

// Generated 26/09/2013 09:21:28 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InstructoresDocumentos generated by hbm2java
 */
@Entity
@Table(name = "INSTRUCTORES_DOCUMENTOS", catalog = "astecadb")
public class InstructoresDocumentos implements java.io.Serializable {

	private Integer idInstructorDocumento;
	private Instructores instructores;
	private Docs documento;

	public InstructoresDocumentos() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_INSTRUCTOR_DOCUMENTO", unique = true, nullable = false)
	public Integer getIdInstructorDocumento() {
		return this.idInstructorDocumento;
	}

	public void setIdInstructorDocumento(Integer idInstructorDocumento) {
		this.idInstructorDocumento = idInstructorDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_INSTRUCTOR")
	public Instructores getInstructores() {
		return this.instructores;
	}

	public void setInstructores(Instructores instructores) {
		this.instructores = instructores;
	}

	/**
	 * @return the documento
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DOCUMENTO")
	public Docs getDocumento() {
		return documento;
	}

	/**
	 * @param documento
	 *            the documento to set
	 */
	public void setDocumento(Docs documento) {
		this.documento = documento;
	}

}
