package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotificacionesTipos generated by hbm2java
 */
@Entity
@Table(name="notificaciones_tipos"
    ,catalog="astecadb"
)
public class NotificacionesTipos  implements java.io.Serializable {


     private short idNotifTipo;
     private String nombre;
     private Set<Notificaciones> notificacioneses = new HashSet<Notificaciones>(0);

    public NotificacionesTipos() {
    }

	
    public NotificacionesTipos(short idNotifTipo) {
        this.idNotifTipo = idNotifTipo;
    }
    public NotificacionesTipos(short idNotifTipo, String nombre, Set<Notificaciones> notificacioneses) {
       this.idNotifTipo = idNotifTipo;
       this.nombre = nombre;
       this.notificacioneses = notificacioneses;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_NOTIF_TIPO", unique=true, nullable=false)
    public short getIdNotifTipo() {
        return this.idNotifTipo;
    }
    
    public void setIdNotifTipo(short idNotifTipo) {
        this.idNotifTipo = idNotifTipo;
    }
    
    @Column(name="NOMBRE", length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="notificacionesTipos")
    public Set<Notificaciones> getNotificacioneses() {
        return this.notificacioneses;
    }
    
    public void setNotificacioneses(Set<Notificaciones> notificacioneses) {
        this.notificacioneses = notificacioneses;
    }




}


