package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProgramaEstMaterias generated by hbm2java
 */
@Entity
@Table(name="PROGRAMA_EST_MATERIAS"
    ,catalog="astecadb"
)
public class ProgramaEstMaterias  implements java.io.Serializable {


     private int idProgrEstMat;
     private ProgramaEstudios programaEstudios;
     private Materias materias;
     private Integer horasTeoria;
     private Integer horasPractica;

    public ProgramaEstMaterias() {
    }

	
    public ProgramaEstMaterias(int idProgrEstMat) {
        this.idProgrEstMat = idProgrEstMat;
    }
    public ProgramaEstMaterias(int idProgrEstMat, ProgramaEstudios programaEstudios, Materias materias, Integer horasTeoria, Integer horasPractica) {
       this.idProgrEstMat = idProgrEstMat;
       this.programaEstudios = programaEstudios;
       this.materias = materias;
       this.horasTeoria = horasTeoria;
       this.horasPractica = horasPractica;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_PROGR_EST_MAT", unique=true, nullable=false)
    public int getIdProgrEstMat() {
        return this.idProgrEstMat;
    }
    
    public void setIdProgrEstMat(int idProgrEstMat) {
        this.idProgrEstMat = idProgrEstMat;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROGR_EST")
    public ProgramaEstudios getProgramaEstudios() {
        return this.programaEstudios;
    }
    
    public void setProgramaEstudios(ProgramaEstudios programaEstudios) {
        this.programaEstudios = programaEstudios;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MATERIA")
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }
    
    @Column(name="HORAS_TEORIA")
    public Integer getHorasTeoria() {
        return this.horasTeoria;
    }
    
    public void setHorasTeoria(Integer horasTeoria) {
        this.horasTeoria = horasTeoria;
    }
    
    @Column(name="HORAS_PRACTICA")
    public Integer getHorasPractica() {
        return this.horasPractica;
    }
    
    public void setHorasPractica(Integer horasPractica) {
        this.horasPractica = horasPractica;
    }




}


