package mx.com.asteca.persistencia.entidades;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReporteAulas generated by hbm2java
 */
@Entity
@Table(name = "REPORTE_AULAS", catalog = "astecadb")
public class ReporteAulas implements java.io.Serializable {

	private int idReporteAulas;
	private String instructor;
	private String horas;
	private String mes;

	public ReporteAulas() {
	}

	public ReporteAulas(int idReporteAulas) {
		this.idReporteAulas = idReporteAulas;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idReporteAulas;
		return result;
	}

    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "IDREPORTE_AULAS", unique=true, nullable=false)
	public int getIdReporteAulas() {
		return idReporteAulas;
	}

	public void setIdReporteAulas(int idReporteAulas) {
		this.idReporteAulas = idReporteAulas;
	}

	@Column(name = "INSTRUCTOR")
	public String getInstructor() {
		return instructor;
	}

	public void setInstructor(String instructor) {
		this.instructor = instructor;
	}

	@Column(name = "HORAS")
	public String getHoras() {
		return horas;
	}

	public void setHoras(String horas) {
		this.horas = horas;
	}

	@Column(name = "MES")
	public String getMes() {
		return mes;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ReporteAulas other = (ReporteAulas) obj;
		if (idReporteAulas != other.idReporteAulas)
			return false;
		return true;
	}

}
