package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposInstructores generated by hbm2java
 */
@Entity
@Table(name="tipos_instructores"
    ,catalog="astecadb"
)
public class TiposInstructores  implements java.io.Serializable {


     private short idTipoInstructor;
     private String nombre;
     private Set<Instructores> instructoreses = new HashSet<Instructores>(0);

    public TiposInstructores() {
    }

	
    public TiposInstructores(short idTipoInstructor) {
        this.idTipoInstructor = idTipoInstructor;
    }
    public TiposInstructores(short idTipoInstructor, String nombre, Set<Instructores> instructoreses) {
       this.idTipoInstructor = idTipoInstructor;
       this.nombre = nombre;
       this.instructoreses = instructoreses;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_TIPO_INSTRUCTOR", unique=true, nullable=false)
    public short getIdTipoInstructor() {
        return this.idTipoInstructor;
    }
    
    public void setIdTipoInstructor(short idTipoInstructor) {
        this.idTipoInstructor = idTipoInstructor;
    }
    
    @Column(name="NOMBRE", length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tiposInstructores")
    public Set<Instructores> getInstructoreses() {
        return this.instructoreses;
    }
    
    public void setInstructoreses(Set<Instructores> instructoreses) {
        this.instructoreses = instructoreses;
    }




}


