package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Administrativos generated by hbm2java
 */
@Entity
@Table(name="ADMINISTRATIVOS"
    ,catalog="astecadb"
)
public class Administrativos  implements java.io.Serializable {


     private int idAdmin;
     private Domicilios domicilios;
     private Personas personas;
     private String noEmpleado;

    public Administrativos() {
    }

	
    public Administrativos(int idAdmin) {
        this.idAdmin = idAdmin;
    }
    public Administrativos(int idAdmin, Domicilios domicilios, Personas personas, String noEmpleado) {
       this.idAdmin = idAdmin;
       this.domicilios = domicilios;
       this.personas = personas;
       this.noEmpleado = noEmpleado;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_ADMIN", unique=true, nullable=false)
    public int getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(int idAdmin) {
        this.idAdmin = idAdmin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOMICILIO")
    public Domicilios getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Domicilios domicilios) {
        this.domicilios = domicilios;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERSONA")
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    
    @Column(name="NO_EMPLEADO", length=20)
    public String getNoEmpleado() {
        return this.noEmpleado;
    }
    
    public void setNoEmpleado(String noEmpleado) {
        this.noEmpleado = noEmpleado;
    }




}


