package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AlumnosCursos generated by hbm2java
 */
@Entity
@Table(name="ALUMNOS_CURSOS"
    ,catalog="astecadb"
)
public class AlumnosCursos  implements java.io.Serializable {


     private int idAlumnoCurso;
     private Alumnos alumnos;
     private Cursos cursos;

    public AlumnosCursos() {
    }

	
    public AlumnosCursos(int idAlumnoCurso) {
        this.idAlumnoCurso = idAlumnoCurso;
    }
    public AlumnosCursos(int idAlumnoCurso, Alumnos alumnos, Cursos cursos) {
       this.idAlumnoCurso = idAlumnoCurso;
       this.alumnos = alumnos;
       this.cursos = cursos;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_ALUMNO_CURSO", unique=true, nullable=false)
    public int getIdAlumnoCurso() {
        return this.idAlumnoCurso;
    }
    
    public void setIdAlumnoCurso(int idAlumnoCurso) {
        this.idAlumnoCurso = idAlumnoCurso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ALUMNO")
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CURSO")
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }




}


