package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * AsentamientosId generated by hbm2java
 */
@Embeddable
public class AsentamientosId  implements java.io.Serializable {


     private int idAsentamiento;
     private int idMunicipio;
     private int idEstado;

    public AsentamientosId() {
    }

    public AsentamientosId(int idAsentamiento, int idMunicipio, int idEstado) {
       this.idAsentamiento = idAsentamiento;
       this.idMunicipio = idMunicipio;
       this.idEstado = idEstado;
    }
   

    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_ASENTAMIENTO", nullable=false)
    public int getIdAsentamiento() {
        return this.idAsentamiento;
    }
    
    public void setIdAsentamiento(int idAsentamiento) {
        this.idAsentamiento = idAsentamiento;
    }

    @Column(name="ID_MUNICIPIO", nullable=false)
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

    @Column(name="ID_ESTADO", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsentamientosId) ) return false;
		 AsentamientosId castOther = ( AsentamientosId ) other; 
         
		 return (this.getIdAsentamiento()==castOther.getIdAsentamiento())
 && (this.getIdMunicipio()==castOther.getIdMunicipio())
 && (this.getIdEstado()==castOther.getIdEstado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAsentamiento();
         result = 37 * result + this.getIdMunicipio();
         result = 37 * result + this.getIdEstado();
         return result;
   }   


}


