package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AutorizacionesProgrEst generated by hbm2java
 */
@Entity
@Table(name="AUTORIZACIONES_PROGR_EST"
    ,catalog="astecadb"
)
public class AutorizacionesProgrEst  implements java.io.Serializable {


     private int idAutorizacion;
     private Docs docs;
     private ProgramaEstudios programaEstudios;
     private Date fechaUpload;

    public AutorizacionesProgrEst() {
    }

	
    public AutorizacionesProgrEst(int idAutorizacion) {
        this.idAutorizacion = idAutorizacion;
    }
    public AutorizacionesProgrEst(int idAutorizacion, Docs docs, ProgramaEstudios programaEstudios, Date fechaUpload) {
       this.idAutorizacion = idAutorizacion;
       this.docs = docs;
       this.programaEstudios = programaEstudios;
       this.fechaUpload = fechaUpload;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_AUTORIZACION", unique=true, nullable=false)
    public int getIdAutorizacion() {
        return this.idAutorizacion;
    }
    
    public void setIdAutorizacion(int idAutorizacion) {
        this.idAutorizacion = idAutorizacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOC")
    public Docs getDocs() {
        return this.docs;
    }
    
    public void setDocs(Docs docs) {
        this.docs = docs;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROG_EST")
    public ProgramaEstudios getProgramaEstudios() {
        return this.programaEstudios;
    }
    
    public void setProgramaEstudios(ProgramaEstudios programaEstudios) {
        this.programaEstudios = programaEstudios;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_UPLOAD", length=10)
    public Date getFechaUpload() {
        return this.fechaUpload;
    }
    
    public void setFechaUpload(Date fechaUpload) {
        this.fechaUpload = fechaUpload;
    }




}


