package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CapacidadesAlumnos generated by hbm2java
 */
@Entity
@Table(name="CAPACIDADES_ALUMNOS"
    ,catalog="astecadb"
)
public class CapacidadesAlumnos  implements java.io.Serializable {


     private int idCapAlu;
     private Alumnos alumnos;
     private Capacidades capacidades;

    public CapacidadesAlumnos() {
    }

	
    public CapacidadesAlumnos(int idCapAlu) {
        this.idCapAlu = idCapAlu;
    }
    public CapacidadesAlumnos(int idCapAlu, Alumnos alumnos, Capacidades capacidades) {
       this.idCapAlu = idCapAlu;
       this.alumnos = alumnos;
       this.capacidades = capacidades;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CAP_ALU", unique=true, nullable=false)
    public int getIdCapAlu() {
        return this.idCapAlu;
    }
    
    public void setIdCapAlu(int idCapAlu) {
        this.idCapAlu = idCapAlu;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ALUMNO")
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CAPACIDADES")
    public Capacidades getCapacidades() {
        return this.capacidades;
    }
    
    public void setCapacidades(Capacidades capacidades) {
        this.capacidades = capacidades;
    }




}


