package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="astecadb"
)
public class Clientes  implements java.io.Serializable {


     private int idCliente;
     private TiposClientes tiposClientes;
     private String clave;
     private String nombre;
     private String responsable;
     private String telefono;
     private String email;

    public Clientes() {
    }

	
    public Clientes(int idCliente) {
        this.idCliente = idCliente;
    }
    public Clientes(int idCliente, TiposClientes tiposClientes, String clave, String nombre, String responsable, String telefono, String email) {
       this.idCliente = idCliente;
       this.tiposClientes = tiposClientes;
       this.clave = clave;
       this.nombre = nombre;
       this.responsable = responsable;
       this.telefono = telefono;
       this.email = email;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CLIENTE", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_CLIENTE")
    public TiposClientes getTiposClientes() {
        return this.tiposClientes;
    }
    
    public void setTiposClientes(TiposClientes tiposClientes) {
        this.tiposClientes = tiposClientes;
    }
    
    @Column(name="CLAVE", length=20)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="NOMBRE", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="RESPONSABLE", length=50)
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    
    @Column(name="TELEFONO", length=30)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="EMAIL", length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


