package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocsAlumnos generated by hbm2java
 */
@Entity
@Table(name="DOCS_ALUMNOS"
    ,catalog="astecadb"
)
public class DocsAlumnos  implements java.io.Serializable {


     private int idDocAlumno;
     private Docs docs;
     private Alumnos alumnos;
     private Date fechaUpload;

    public DocsAlumnos() {
    }

	
    public DocsAlumnos(int idDocAlumno) {
        this.idDocAlumno = idDocAlumno;
    }
    public DocsAlumnos(int idDocAlumno, Docs docs, Alumnos alumnos, Date fechaUpload) {
       this.idDocAlumno = idDocAlumno;
       this.docs = docs;
       this.alumnos = alumnos;
       this.fechaUpload = fechaUpload;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_DOC_ALUMNO", unique=true, nullable=false)
    public int getIdDocAlumno() {
        return this.idDocAlumno;
    }
    
    public void setIdDocAlumno(int idDocAlumno) {
        this.idDocAlumno = idDocAlumno;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DOC")
    public Docs getDocs() {
        return this.docs;
    }
    
    public void setDocs(Docs docs) {
        this.docs = docs;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ALUMNO")
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_UPLOAD", length=10)
    public Date getFechaUpload() {
        return this.fechaUpload;
    }
    
    public void setFechaUpload(Date fechaUpload) {
        this.fechaUpload = fechaUpload;
    }




}


