package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estatus generated by hbm2java
 */
@Entity
@Table(name="ESTATUS"
    ,catalog="astecadb"
)
public class Estatus  implements java.io.Serializable {


     private short idEstatus;
     private String descEstatus;
     private String obsEstatus;
     private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);
     private Set<Certificados> certificadoses = new HashSet<Certificados>(0);
     private Set<Docs> docses = new HashSet<Docs>(0);

    public Estatus() {
    }

	
    public Estatus(short idEstatus) {
        this.idEstatus = idEstatus;
    }
    public Estatus(short idEstatus, String descEstatus, String obsEstatus, Set<Alumnos> alumnoses, Set<Certificados> certificadoses, Set<Docs> docses) {
       this.idEstatus = idEstatus;
       this.descEstatus = descEstatus;
       this.obsEstatus = obsEstatus;
       this.alumnoses = alumnoses;
       this.certificadoses = certificadoses;
       this.docses = docses;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_ESTATUS", unique=true, nullable=false)
    public short getIdEstatus() {
        return this.idEstatus;
    }
    
    public void setIdEstatus(short idEstatus) {
        this.idEstatus = idEstatus;
    }
    
    @Column(name="DESC_ESTATUS", length=20)
    public String getDescEstatus() {
        return this.descEstatus;
    }
    
    public void setDescEstatus(String descEstatus) {
        this.descEstatus = descEstatus;
    }
    
    @Column(name="OBS_ESTATUS", length=20)
    public String getObsEstatus() {
        return this.obsEstatus;
    }
    
    public void setObsEstatus(String obsEstatus) {
        this.obsEstatus = obsEstatus;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estatus")
    public Set<Alumnos> getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set<Alumnos> alumnoses) {
        this.alumnoses = alumnoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estatus")
    public Set<Certificados> getCertificadoses() {
        return this.certificadoses;
    }
    
    public void setCertificadoses(Set<Certificados> certificadoses) {
        this.certificadoses = certificadoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estatus")
    public Set<Docs> getDocses() {
        return this.docses;
    }
    
    public void setDocses(Set<Docs> docses) {
        this.docses = docses;
    }




}


