package mx.com.asteca.persistencia.entidades;
// Generated 1/09/2013 05:14:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name="estados"
    ,catalog="astecadb"
)
public class Estados  implements java.io.Serializable {


     private Integer idEstado;
     private Paises paises;
     private String nombre;
     private Short activo;
     private String clave;
     private Set<Municipios> municipioses = new HashSet<Municipios>(0);

    public Estados() {
    }
    
    public Estados(int randomInt){
    	idEstado = randomInt;
    }

    public Estados(Paises paises, String nombre, Short activo, String clave, Set<Municipios> municipioses) {
       this.paises = paises;
       this.nombre = nombre;
       this.activo = activo;
       this.clave = clave;
       this.municipioses = municipioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_ESTADO", unique=true, nullable=false)
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PAIS")
    public Paises getPaises() {
        return this.paises;
    }
    
    public void setPaises(Paises paises) {
        this.paises = paises;
    }
    
    @Column(name="NOMBRE", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="ACTIVO")
    public Short getActivo() {
        return this.activo;
    }
    
    public void setActivo(Short activo) {
        this.activo = activo;
    }
    
    @Column(name="CLAVE", length=15)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Municipios> getMunicipioses() {
        return this.municipioses;
    }
    
    public void setMunicipioses(Set<Municipios> municipioses) {
        this.municipioses = municipioses;
    }




}


