package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ultima Actualizacion
 * Modulos generated by hbm2java
 */
@Entity
@Table(name="modulos"
    ,catalog="astecadb"
)
public class Modulos  implements java.io.Serializable {


     private int idModulo;
     private String nombre;
     private String dsc;

    public Modulos() {
    }

	
    public Modulos(int idModulo) {
        this.idModulo = idModulo;
    }
    public Modulos(int idModulo, String nombre, String dsc) {
       this.idModulo = idModulo;
       this.nombre = nombre;
       this.dsc = dsc;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_MODULO", unique=true, nullable=false)
    public int getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(int idModulo) {
        this.idModulo = idModulo;
    }
    
    @Column(name="NOMBRE", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DSC", length=50)
    public String getDsc() {
        return this.dsc;
    }
    
    public void setDsc(String dsc) {
        this.dsc = dsc;
    }




}


