package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modulos generated by hbm2java
 */
@Entity
@Table(name="MODULOS"
    ,catalog="astecadb"
)
public class Modulos  implements java.io.Serializable {


     private int idModulo;
     private String nombre;
     private String dsc;
     private String ruta;
     private String columna_1;
     private String columna_2;
     private String columna_3;

    public Modulos() {
    }

	
    public Modulos(int idModulo) {
        this.idModulo = idModulo;
    }
    public Modulos(int idModulo, String nombre, String dsc) {
       this.idModulo = idModulo;
       this.nombre = nombre;
       this.dsc = dsc;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_MODULO", unique=true, nullable=false)
    public int getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(int idModulo) {
        this.idModulo = idModulo;
    }
    
    @Column(name="NOMBRE", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DSC", length=50)
    public String getDsc() {
        return this.dsc;
    }
    
    public void setDsc(String dsc) {
        this.dsc = dsc;
    }


	/**
	 * @return the ruta
	 */
    @Column(name="RUTA", length=100)
	public String getRuta() {
		return ruta;
	}


	/**
	 * @param ruta the ruta to set
	 */
	public void setRuta(String ruta) {
		this.ruta = ruta;
	}


	/**
	 * @return the columna_1
	 */
	@Column(name="COLUMNA_1", length=50)
	public String getColumna_1() {
		return columna_1;
	}


	/**
	 * @param columna_1 the columna_1 to set
	 */
	public void setColumna_1(String columna_1) {
		this.columna_1 = columna_1;
	}


	/**
	 * @return the columna_2
	 */
	@Column(name="COLUMNA_2", length=50)
	public String getColumna_2() {
		return columna_2;
	}


	/**
	 * @param columna_2 the columna_2 to set
	 */
	public void setColumna_2(String columna_2) {
		this.columna_2 = columna_2;
	}


	/**
	 * @return the columna_3
	 */
	@Column(name="COLUMNA_3", length=50)
	public String getColumna_3() {
		return columna_3;
	}


	/**
	 * @param columna_3 the columna_3 to set
	 */
	public void setColumna_3(String columna_3) {
		this.columna_3 = columna_3;
	}




}


