package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotificacionesEstados generated by hbm2java
 */
@Entity
@Table(name="notificaciones_estados"
    ,catalog="astecadb"
)
public class NotificacionesEstados  implements java.io.Serializable {


     private short idNotifEdo;
     private String nombre;
     private Set<Notificaciones> notificacioneses = new HashSet<Notificaciones>(0);

    public NotificacionesEstados() {
    }

	
    public NotificacionesEstados(short idNotifEdo) {
        this.idNotifEdo = idNotifEdo;
    }
    public NotificacionesEstados(short idNotifEdo, String nombre, Set<Notificaciones> notificacioneses) {
       this.idNotifEdo = idNotifEdo;
       this.nombre = nombre;
       this.notificacioneses = notificacioneses;
    }
   
     @Id 
    
    @Column(name="ID_NOTIF_EDO", unique=true, nullable=false)
    public short getIdNotifEdo() {
        return this.idNotifEdo;
    }
    
    public void setIdNotifEdo(short idNotifEdo) {
        this.idNotifEdo = idNotifEdo;
    }
    
    @Column(name="NOMBRE", length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="notificacionesEstados")
    public Set<Notificaciones> getNotificacioneses() {
        return this.notificacioneses;
    }
    
    public void setNotificacioneses(Set<Notificaciones> notificacioneses) {
        this.notificacioneses = notificacioneses;
    }




}


