package mx.com.asteca.persistencia.entidades;
// Generated 31/07/2013 11:41:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personas generated by hbm2java
 */
@Entity
@Table(name="personas"
    ,catalog="astecadb"
)
public class Personas  implements java.io.Serializable {


     private int idPersona;
     private Date fechaNac;
     private String lugarNac;
     private String curp;
     private String rfc;
     private String ife;
     private String pasaporte;
     private String email;
     private String nombre;
     private String apellidoP;
     private String apellidoM;
     private Set<Instructores> instructoreses = new HashSet<Instructores>(0);
     private Set<RolesModUsuarios> rolesModUsuarioses = new HashSet<RolesModUsuarios>(0);
     private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);
     private Set<Referencias> referenciases = new HashSet<Referencias>(0);
     private Set<Administrativos> administrativoses = new HashSet<Administrativos>(0);
     private Set<InstitutoContactos> institutoContactoses = new HashSet<InstitutoContactos>(0);

    public Personas() {
    }

	
    public Personas(int idPersona) {
        this.idPersona = idPersona;
    }
    public Personas(int idPersona, Date fechaNac, String lugarNac, String curp, String rfc, String ife, String pasaporte, String email, String nombre, String apellidoP, String apellidoM, Set<Instructores> instructoreses, Set<RolesModUsuarios> rolesModUsuarioses, Set<Alumnos> alumnoses, Set<Referencias> referenciases, Set<Administrativos> administrativoses, Set<InstitutoContactos> institutoContactoses) {
       this.idPersona = idPersona;
       this.fechaNac = fechaNac;
       this.lugarNac = lugarNac;
       this.curp = curp;
       this.rfc = rfc;
       this.ife = ife;
       this.pasaporte = pasaporte;
       this.email = email;
       this.nombre = nombre;
       this.apellidoP = apellidoP;
       this.apellidoM = apellidoM;
       this.instructoreses = instructoreses;
       this.rolesModUsuarioses = rolesModUsuarioses;
       this.alumnoses = alumnoses;
       this.referenciases = referenciases;
       this.administrativoses = administrativoses;
       this.institutoContactoses = institutoContactoses;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_PERSONA", unique=true, nullable=false)
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_NAC", length=10)
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    
    @Column(name="LUGAR_NAC", length=50)
    public String getLugarNac() {
        return this.lugarNac;
    }
    
    public void setLugarNac(String lugarNac) {
        this.lugarNac = lugarNac;
    }
    
    @Column(name="CURP", length=20)
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    
    @Column(name="RFC", length=20)
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    
    @Column(name="IFE", length=20)
    public String getIfe() {
        return this.ife;
    }
    
    public void setIfe(String ife) {
        this.ife = ife;
    }
    
    @Column(name="PASAPORTE", length=30)
    public String getPasaporte() {
        return this.pasaporte;
    }
    
    public void setPasaporte(String pasaporte) {
        this.pasaporte = pasaporte;
    }
    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="NOMBRE", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="APELLIDO_P", length=30)
    public String getApellidoP() {
        return this.apellidoP;
    }
    
    public void setApellidoP(String apellidoP) {
        this.apellidoP = apellidoP;
    }
    
    @Column(name="APELLIDO_M", length=30)
    public String getApellidoM() {
        return this.apellidoM;
    }
    
    public void setApellidoM(String apellidoM) {
        this.apellidoM = apellidoM;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personas")
    public Set<Instructores> getInstructoreses() {
        return this.instructoreses;
    }
    
    public void setInstructoreses(Set<Instructores> instructoreses) {
        this.instructoreses = instructoreses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personas")
    public Set<RolesModUsuarios> getRolesModUsuarioses() {
        return this.rolesModUsuarioses;
    }
    
    public void setRolesModUsuarioses(Set<RolesModUsuarios> rolesModUsuarioses) {
        this.rolesModUsuarioses = rolesModUsuarioses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personas")
    public Set<Alumnos> getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set<Alumnos> alumnoses) {
        this.alumnoses = alumnoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personas")
    public Set<Referencias> getReferenciases() {
        return this.referenciases;
    }
    
    public void setReferenciases(Set<Referencias> referenciases) {
        this.referenciases = referenciases;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personas")
    public Set<Administrativos> getAdministrativoses() {
        return this.administrativoses;
    }
    
    public void setAdministrativoses(Set<Administrativos> administrativoses) {
        this.administrativoses = administrativoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personas")
    public Set<InstitutoContactos> getInstitutoContactoses() {
        return this.institutoContactoses;
    }
    
    public void setInstitutoContactoses(Set<InstitutoContactos> institutoContactoses) {
        this.institutoContactoses = institutoContactoses;
    }




}


