package mx.com.asteca.comun.dto;

import java.util.List;
import java.util.Set;

/**
 * Institutos generated by hbm2java
 */
public class InstitutoDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idInstituto;
	private String nombre;
	private String razonSocial;
	private String rfc;
	private DomicilioDTO dtoDomicilio;
	private String fax;
	private List<InstitutoContactoDTO> listContactos;

	public InstitutoDTO() {
	}

	public InstitutoDTO(int idInstituto) {
		this.idInstituto = idInstituto;
	}

	public InstitutoDTO(int idInstituto, String nombre, String razonSocial,
			String rfc,  String fax
			) {
		this.idInstituto = idInstituto;
		this.nombre = nombre;
		this.razonSocial = razonSocial;
		this.rfc = rfc;
		this.fax = fax;
	}

	public int getIdInstituto() {
		return this.idInstituto;
	}

	public void setIdInstituto(int idInstituto) {
		this.idInstituto = idInstituto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * @return the dtoDomicilio
	 */
	public DomicilioDTO getDtoDomicilio() {
		return dtoDomicilio;
	}

	/**
	 * @param dtoDomicilio the dtoDomicilio to set
	 */
	public void setDtoDomicilio(DomicilioDTO dtoDomicilio) {
		this.dtoDomicilio = dtoDomicilio;
	}

	/**
	 * @return the listContactos
	 */
	public List<InstitutoContactoDTO> getListContactos() {
		return listContactos;
	}

	/**
	 * @param listContactos the listContactos to set
	 */
	public void setListContactos(List<InstitutoContactoDTO> listContactos) {
		this.listContactos = listContactos;
	}

}
