package mx.com.asteca.comun.dto;


/**
 * InstitutoContactos generated by hbm2java
 */
public class InstitutoContactosDTO implements java.io.Serializable {

	private int idInstCont;
	private InstitutoPuestosDTO institutoPuestos;
	private PersonaDTO PersonasDTO;
	private InstitutoDTO institutos;

	public InstitutoContactosDTO() {
	}

	public InstitutoContactosDTO(int idInstCont) {
		this.idInstCont = idInstCont;
	}

	public InstitutoContactosDTO(int idInstCont,
			InstitutoPuestosDTO institutoPuestos, PersonaDTO PersonasDTO,
			InstitutoDTO institutos) {
		this.idInstCont = idInstCont;
		this.institutoPuestos = institutoPuestos;
		this.PersonasDTO = PersonasDTO;
		this.institutos = institutos;
	}

	public int getIdInstCont() {
		return this.idInstCont;
	}

	public void setIdInstCont(int idInstCont) {
		this.idInstCont = idInstCont;
	}

	public InstitutoPuestosDTO getInstitutoPuestos() {
		return this.institutoPuestos;
	}

	public void setInstitutoPuestos(InstitutoPuestosDTO institutoPuestos) {
		this.institutoPuestos = institutoPuestos;
	}

	public PersonaDTO getPersonasDTO() {
		return this.PersonasDTO;
	}

	public void setPersonasDTO(PersonaDTO PersonasDTO) {
		this.PersonasDTO = PersonasDTO;
	}

	public InstitutoDTO getInstitutos() {
		return this.institutos;
	}

	public void setInstitutos(InstitutoDTO institutos) {
		this.institutos = institutos;
	}

}
