package mx.com.asteca.comun;

/**
 * @author JAC, HJCH, RIG
 *
 */
public class Constantes {

	public static final String ASSEMBLER_CLIENTE="assemblerCliente";
	public static final String ASSEMBLER_CATGRAL="assemblerCatGral";
	public static final String ASSEMBLER_INSTITUTO="assemblerInstituto";
	public static final String ASSEMBLER_ESTADOS="assemblerEstados";
	public static final String ASSEMBLER_MUNICIPIOS="assemblerMunicipios";
	public static final String ASSEMBLER_ASENTAMIENTOS="assemblerAsentamientos";
	public static final String ASSEMBLER_DOMICILIO="assemblerDomicilio";
	public static final String ASSEMBLER_ESTATUS="assemblerEstatus";
	public static final String ASSEMBLER_EQUIPO="assemblerEquipo";
	public static final String ASSEMBLER_FAMILIA="assemblerFamilia";
	public static final String ASSEMBLER_PERSONA="assemblerPersona";
	public static final String ASSEMBLER_PAISES="assemblerPaises";
	public static final String ASSEMBLER_NOTIFICACION="assemblerNotificacion";
	public static final String ASSEMBLER_NOTIFICACION_ESTADO="assemblerNotificacionEstado";
	public static final String ASSEMBLER_NOTIFICACION_TIPO="assemblerNotificacionTipo";	
	public static final String ASSEMBLER_TIPO_CLIENTE="assemblerTipoCliente";
	public static final String ASSEMBLER_AULAS="assemblerAulas";
	public static final String ASSEMBLER_CAPACIDADES="assemblerCapacidades";
	public static final String ASSEMBLER_ESTUDIO="assemblerEstudio";
	public static final String ASSEMBLER_TIPO_ESTUDIO="assemblerTipoEstudios";
	public static final String ASSEMBLER_TIPO_LICENCIA="assemblerTipoLicencia";
	public static final String ASSEMBLER_ALUMNO="assemblerAlumno";
	public static final String ASSEMBLER_DOCS="assemblerDocs";
	public static final String ASSEMBLER_REFERENCIAS="assemblerReferencias";
	public static final String ASSEMBLER_MODULO="assemblerModulo";
	public static final String ASSEMBLER_MODULOS="assemblerModulos";
	public static final String ASSEMBLER_CONF_DESCARGAS="assemblerConfDescargas";
	public static final String ASSEMBLER_ADMINISTRATIVOS="assemblerAdministrativos";
	public static final String ASSEMBLER_MATERIAS="assemblerMaterias";
	public static final String ASSEMBLER_MATERIAS_REGISTROS="assemblerMateriasRegistros";
	public static final String ASSEMBLER_PROGRAMA_ESTUDIOS="assemblerProgramaEstudios";
	public static final String ASSEMBLER_AUTORIZACION_PROGR_EST="assemblerAutProgrEst";
	public static final String ASSEMBLER_PROGRAMA_ESTUDIOS_MATERIAS_REG="assemblerProgramaEstudiosMateriasReg";
	public static final String ASSEMBLER_PERMISOS="assemblerPermisos";
	public static final String ASSEMBLER_ROLES="assemblerRoles";
	public static final String ASSEMBLER_ROLES_MODULOS="assemblerRolesModulos";
	public static final String ASSEMBLER_ROLES_MOD_USUARIOS="assmblerRolesModUsuarios";
	public static final String ASSEMBLER_ROLES_MOD_PERMISOS_SOBRE="assemblerRolesModPermisosSobre";
	public static final String ASSEMBLER_ROLES_MOD_PERMISOS_USR="assemblerRolesModPermisosUsr";
	public static final String ERROR_OBTENIENDO_LISTA_CATALOGO="No se pudo obtener el catalogo.";
	public static final String ERROR_NUEVO_REGISTRO="No se pudo completar el nuevo registro.";
	public static final String BEAN_EQUIPO="beanEquipo";
	public static final String BEAN_NOTIFICACION="beanNotificacion";
	public static final String BEAN_CLIENTES="beanClientes";
	public static final String BEAN_ESTADOS="beanEstados";
	public static final String BEAN_MUNICIPIOS="beanMunicipios";
	public static final String BEAN_CAT_GRAL="beanCatGral";
	public static final String BEAN_AULAS="beanAulas";
	public static final String BEAN_ALUMNO="beanAlumno";
	public static final String BEAN_MENU="menuBean";
	public static final String BEAN_PERFIL="perfilBean";
	public static final String BEAN_PERMISO_ROL="permisoRolBean";
	public static final String BEAN_CURSO="beanCurso";
	public static final String ERROR_NO_HAY_SELECCION="Debes seleccionar al menos un elemento.";
	public static final String ERROR_UPDATE_REGISTRO="Error guardando.";
	public static final String ERROR_DELETE_REGISTRO="Error borrando.";
	public static final String ERROR_SELECT_ITEM="Error al obtener el elemento seleccionado";
	public static final String BEAN_TREE="beanTree";
	public static final String BEAN_ADMINISTRATIVOS="beanAdmin";
	public static final String BEAN_INSTITUTOS="beanInstituto";
	public static final String BEAN_PROGRAMA_ESTUDIOS="beanProgramaEstudios";
	public static final String ERROR_NECESITAS_SELECCIONAR_UN_PAIS="Necesitas seleccionar un pais";
	public static final String ERROR_NECESITAS_SELECCIONAR_UN_EDO="Necesitas seleccionar un estado";
	public static final String ERROR_NECESITAS_SELECCIONAR_UN_CLIENTE="Necesitas seleccionar un cliente";
	public static final String ERROR_NECESITAS_SELECCIONAR_UN_TIPO_CLIENTE="Necesitas seleccionar un tipo de cliente";
	public static final String ERROR_NECESITAS_SELECCIONAR_UN_TIPO_EQUIPO="Necesitas seleccionar un tipo de equipos";
	public static final String ERROR_NECESITAS_SELECCIONAR_UNA_SEDE="Necesitas seleccionar una sede";
	public static final String ERROR_FORMATO_NUMERO="Debes introducir una cantidad valida";
	public static final String NUEVO_REGISTRO_EXITOSO="Se ha insertado un nuevo registro exitosamente";
	public static final String DELETE_REGISTRO_EXITOSO="Se ha eliminado el registro exitosamente";
	public static final String UPDATE_REGISTRO_EXITOSO="Se ha actualizado el registro exitosamente";
	public static final String MESSAGE_TITLE_INFO="Info";
	public static final String MESSAGE_TITLE_ERROR="Error";
	public static final String MESSAGE_TITLE_WARNING="Advertencia";
	public static final String ERROR_LOGIN="Usuario y/o Contraseña no validos";
	public static final String ERROR_AUTENTICACION="Falló Autenticación";
	public static final String BEAN_LOGIN="beanLogin";
	public static final String MENU_ITEM_PREFIX="mn_item_";
	public static final String MENU_ITEM_PROCESS="@this";
	public static final String MENU_ITEM_UPDATE="@all";
	public static final String BEAN_REPORTE_ALUMNO="beanReporteAlumno";
	public static final String BEAN_REPORTE_AULA="beanReporteAula";
	public static final String BEAN_REPORTE_CURSOS="beanReporteCursos";
	public static final String BEAN_REPORTE_MENSUAL="beanReporteMensual";
	public static final String BEAN_REPORTE_INSTRUCTOR="beanReporteInstructor";
}
